version: "2"
services:
  network-server:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/network-server
      - ./configuration/:/etc/loraserver
    links:
      - postgres
      - redis
      - mosquitto
    tty: true

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=loraserver
      - POSTGRES_USER=loraserver
      - POSTGRES_DB=loraserver

  redis:
    image: redis:3.0.7-alpine

  mosquitto:
    image: ansi/mosquitto
