version: "2"
services:
  network-server:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/network-server
      - ./configuration/:/etc/loraserver
    links:
      - postgresql
      - redis
      - mosquitto
    tty: true

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=loraserver
      - POSTGRES_USER=loraserver
      - POSTGRES_DB=loraserver

  redis:
    image: redis:5-alpine

  mosquitto:
    image: ansi/mosquitto
