version: 2
jobs:
  test:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: run tests
          command: docker-compose run --rm loraserver make test

  deploy:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: compile distributable binaries
          command: docker-compose run --rm loraserver make dist
      - run:
          name: upload binaries to s3
          command: aws s3 sync dist/upload s3://builds.loraserver.io/loraserver

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
